// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SaveAnywhere.SaveData {

  /// <summary>Holder for reflection information generated from Common.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for Common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxDb21tb24ucHJvdG8iHwoHVmVjdG9yMhIJCgF4GAEgASgCEgkKAXkYAiAB",
            "KAIiHAoFQ29sb3ISEwoLcGFja2VkVmFsdWUYASABKA1CGKoCFVNhdmVBbnl3",
            "aGVyZS5TYXZlRGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
            new pbr::GeneratedCodeInfo(typeof(global::SaveAnywhere.SaveData.Vector2), global::SaveAnywhere.SaveData.Vector2.Parser, new[]{ "X", "Y" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::SaveAnywhere.SaveData.Color), global::SaveAnywhere.SaveData.Color.Parser, new[]{ "PackedValue" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Vector2 : pb::IMessage<Vector2> {
    private static readonly pb::MessageParser<Vector2> _parser = new pb::MessageParser<Vector2>(() => new Vector2());
    public static pb::MessageParser<Vector2> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::SaveAnywhere.SaveData.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Vector2() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Vector2(Vector2 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
    }

    public Vector2 Clone() {
      return new Vector2(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Vector2);
    }

    public bool Equals(Vector2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= X.GetHashCode();
      if (Y != 0F) hash ^= Y.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    public void MergeFrom(Vector2 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Color : pb::IMessage<Color> {
    private static readonly pb::MessageParser<Color> _parser = new pb::MessageParser<Color>(() => new Color());
    public static pb::MessageParser<Color> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::SaveAnywhere.SaveData.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Color() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Color(Color other) : this() {
      packedValue_ = other.packedValue_;
    }

    public Color Clone() {
      return new Color(this);
    }

    /// <summary>Field number for the "packedValue" field.</summary>
    public const int PackedValueFieldNumber = 1;
    private uint packedValue_;
    public uint PackedValue {
      get { return packedValue_; }
      set {
        packedValue_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Color);
    }

    public bool Equals(Color other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PackedValue != other.PackedValue) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (PackedValue != 0) hash ^= PackedValue.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (PackedValue != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PackedValue);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (PackedValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PackedValue);
      }
      return size;
    }

    public void MergeFrom(Color other) {
      if (other == null) {
        return;
      }
      if (other.PackedValue != 0) {
        PackedValue = other.PackedValue;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PackedValue = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
